version: '3.8'
services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: vidalme/nodeapp:v1
    ports:
      - "3000:3000"
    volumes:
      - ./dt:/app/dt

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - livraria_db:/data/db

volumes:
  livraria_db: