version: '3.8'
services:


  proxy:
    build: 
      context: .
      dockerfile: proxy.dockerfile

    # image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./html/:/usr/share/nginx/html/
      # - type: bind
      #   source: ./proxy/nginx.conf
      #   target: /etc/nginx/nginx.conf
      #   read_only: true


  backend:
    build: 
      context: .
    image: vidalme/nodeapp:v1
    ports:
      - "3000:3000"
    volumes:
      - ./dt:/app/dt
    networks:
      - front-tier
      - back-tier

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - livraria_db:/data/db
    networks:
      - back-tier


volumes:
  livraria_db:

networks:
  front-tier:
  back-tier: